export const CATEGORIES = [
  {
    id: 'Electrical',
    name: 'Electrical',
    icon: 'Zap',
    description: 'Fans, lights, sockets, switches, wiring issues',
    problems: [
      'Fan not working',
      'Light not working',
      'Switch damaged',
      'Socket not working',
      'AC problem',
      'Power trip / MCB tripped',
      'Other',
    ],
  },
  {
    id: 'Plumbing',
    name: 'Plumbing',
    icon: 'Droplets',
    description: 'Taps, pipes, leakage, showers, flush systems',
    problems: [
      'Water leakage',
      'Tap not working',
      'Flush problem',
      'Drain blockage',
      'Shower problem',
      'Pipe burst',
      'Other',
    ],
  },
  {
    id: 'Cleaning',
    name: 'Cleaning',
    icon: 'Sparkles',
    description: 'Room, corridor, washroom cleanliness and waste disposal',
    problems: [
      'Room cleaning needed',
      'Corridor trash overflow',
      'Bathroom sanitization needed',
      'Dustbin clearance',
      'Cobwebs / pest cleanup',
      'Other',
    ],
  },
  {
    id: 'Furniture',
    name: 'Furniture',
    icon: 'Armchair',
    description: 'Beds, study tables, chairs, cupboards, doors',
    problems: [
      'Broken cot / bed frame',
      'Study chair damaged',
      'Study table broken',
      'Cupboard latch / lock broken',
      'Curtain rod detached',
      'Other',
    ],
  },
  {
    id: 'Internet/Wi-Fi',
    name: 'Internet / Wi-Fi',
    icon: 'Wifi',
    description: 'Wi-Fi network, LAN ports, connectivity failures',
    problems: [
      'Wi-Fi disconnected',
      'Slow internet speed',
      'Router blinking red',
      'Ethernet port dead',
      'Login portal inaccessible',
      'Other',
    ],
  },
  {
    id: 'Room',
    name: 'Room Facility',
    icon: 'DoorClosed',
    description: 'Doors, windows, paint, ceiling, ventilation',
    problems: [
      'Door lock jammed',
      'Window glass broken',
      'Paint peeling / seepage',
      'Mosquito mesh torn',
      'Balcony latch broken',
      'Other',
    ],
  },
  {
    id: 'Bathroom',
    name: 'Bathroom / Washroom',
    icon: 'Bath',
    description: 'Geysers, mirrors, drains, ventilation, hygiene',
    problems: [
      'Geyser not heating',
      'Water stagnation',
      'Mirror broken',
      'Foul odor / exhaust fan dead',
      'Bathroom door latch broken',
      'Other',
    ],
  },
  {
    id: 'Security',
    name: 'Security & Safety',
    icon: 'Shield',
    description: 'Locks, lost keys, window grills, safety concerns',
    problems: [
      'Lost room key',
      'Window grill loose',
      'CCTV issue in wing',
      'Unauthorized access suspicion',
      'Lock replacement needed',
      'Other',
    ],
  },
  {
    id: 'Water',
    name: 'Water Supply',
    icon: 'GlassWater',
    description: 'Drinking water, cooler, overhead tank supply',
    problems: [
      'No running water in block',
      'Drinking water cooler not working',
      'Turbid / muddy water',
      'Low water pressure',
      'Hot water unavailable',
      'Other',
    ],
  },
  {
    id: 'Other',
    name: 'Other Issues',
    icon: 'HelpCircle',
    description: 'Miscellaneous complaints not covered in above categories',
    problems: ['Noise disturbance', 'Corridor lighting', 'Other'],
  },
];
